version: '3'
services:
  # PHP
  counters-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: counters-app
    image: php:7.4-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www

  # NGINX
  counters-web-server:
    container_name: counters-web-server
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - counters-app

# Network config
#networks:
#  default:
#    driver: bridge