version: '3'
services:
  # PHP
  counters-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: counters-app
    image: php:7.4-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    networks:
      - counters

  # NGINX
  counters-web-server:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: counters-web-server
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    networks:
      - counters
    depends_on:
      - counters-app

# Network config
networks:
  counters:
    driver: bridge